add repohooks to all groups
Using the --groups option with repo init will restrict which repos are
downloaded to only the specified ones.  Unfortunately, the <repohooks>
logic will always fire regardless of the selected group (and cannot be
restricted), which means you'll get an error when trying to upload like:
	ERROR: Couldn't find repo hook: ".../tools/repohooks/pre-upload.py"

Add the repohooks repo to every major active group so that it gets
synced/checked out too.  Hopefully this should cover most teams.

Bug: 28295071
Test: `repo init -g adt-infra && repo sync` pulled down the repohooks repo

Change-Id: If0295d7bbdd2840625fa79a76a5ecf11792a601a